copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_FreeFormAudit.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GenSendMail.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_SendMail.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_DeleteUser.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_FindDuplicates.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GetAllTableInfo.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GetDanglingUserNames.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GraphNewMembersByDay.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GraphNewMembersByMonth.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GraphNewMembersByYear.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GraphNewMembers.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_TransactionsLogAudit.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GenManualCheckForm.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_GetMembershipCancellations.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\AuthorizeDotNet\Admin_BatchAuthNetSend.pl D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\Admin_ManipulateLinkMap.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\MassMail\Admin_BatchMailUsersBeforeRebilling.pl D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\MassMail\ML_GetAllMailSentLog.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\MassMail\ML_GetHtmlSent.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
copy D:\MyData\Personal\Projects\Connections\SourceCode\CgiSource\Perl\Admin\MassMail\ML_GetCampaignSummary.cgi D:\MyData\Personal\Projects\Connections\PersianConnectionsWebDev\admin\cgi-bin\
